version: '3.4'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    environment:
      POSTGRES_DB: simple-db
      POSTGRES_USER: simple-user
      POSTGRES_PASSWORD: simple-password!
    command: -c 'shared_buffers=512MB'
    restart: unless-stopped
  simpleapi:
    build: .
    container_name: simpleapi
    environment:
      CONNECTION_STRING: Host=postgres;Port=5432;Database=simple-db;Username=simple-user;Password=simple-password!
    depends_on:
      - postgres
    ports:
      - "80:80"
  prometheus:
    build: ./Prometheus
    container_name: prometheus
    depends_on:
      - simpleapi
    ports:
      - "9090:9090"
volumes:
  postgres: